### ISSUE TITLE
Please add support for adding symlinks without following them

### ISSUE THREAD

**Issue by roivant-sinanunur** [robkinyon/ruby-packager#5]
When adding a symlink such as

```ruby
file {
    source 'symlink-to-some-program'
    dest '/usr/bin/some-program'
}
```
where the target of the link does not exist on the system where the package is being produced, I get 

```text
Errno::ENOENT: No such file or directory @ rb_file_s_stat - /.../symlink-to-some-program
```
even though the link itself exists. Please add support for adding such links without following them.

**Comment by robkinyon** [comment]
Released as 0.1.3
